### ISSUE TITLE
CreatingAvatarModel

### ISSUE THREAD

**Issue by antonkazakov** [bonusdev/BattleOfMindsGame#1]
https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarModel.kt#L19

Советую использовать constructor injection вместо field injection там где это возможно. Про плюсы и минусы можешь почитать здесь https://softwareengineering.stackexchange.com/questions/300706/dependency-injection-field-injection-vs-constructor-injection

https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarModel.kt#L28

Непонятно зачем тебе Picasso в Model. К тому же твой слой модель ничего не должен знать про вью и прочие слои которые находятся выше него. Поэтому советую перенести загрузку изображений во вью.

https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarModel.kt#L37

Лучше инжектить не Database, а конкретные Dao.

**Comment by bonusdev** [comment]
[Fixed](https://github.com/bonusdev/BattleOfMindsGame/commit/5313efd6d7af8aaa06e27aaf9ca599c1d986c2e4)
