### ISSUE TITLE
CreatingAvatarViewModel

### ISSUE THREAD

**Issue by antonkazakov** [bonusdev/BattleOfMindsGame#2]
https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarViewModel.kt#L29

Лучше не смешивать порядок членов класса. Например сначала идут статик переменные, затем обычные переменные, затем функции.

https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarViewModel.kt#L35

MutableLiveData обязательно должна быть private. Иначе заэмитить эвент сможет любой класс у которого есть инстанс CreatingAvatarViewModel. Нужно понизить скоуп видимости MutableLiveData до private и добавить паблик проперти типа LiveData, на который смогут подписываться другие классы, но эмитить айтемы они не смогут.

https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarViewModel.kt#L43

Constructor Injection > Field Injection

https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarViewModel.kt#L50

Почему ты решил строить граф даггера из ViewModel? 

https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarViewModel.kt#L112

Дублирование кода с 119 строкой

https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarViewModel.kt#L112

Почему ты решил взять и корутины и РХ и бонусом лайвдату?

https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarViewModel.kt#L153

Зачем это эмитить во фрагмент из VM если можно создать этот интент сразу во фрагменте?

https://github.com/bonusdev/BattleOfMindsGame/blob/18845793092b9c998fc143825d5c378f22e23b93/app/src/main/java/com/bonusgaming/battleofmindskotlin/creating_avatar/CreatingAvatarViewModel.kt#L126

У тебя не отменяются джобы и не отписываются РХ диспозаблы.

**Comment by bonusdev** [comment]
Корутины, rx и лайвдата использовал просто потому, что с корутинами код идет последовательно и понятно, rx работает с бд, а лайвдата отменяет подписку сама. То есть там где удобно было там и использовал. Насколько я понял, так не надо делать? (наверное из за того, что это сложно тестируется?)

**Comment by bonusdev** [comment]
Интент создаю там, чтобы тестировать потом. Подумал, что формирование интента хорошо бы протестировать потом.

**Comment by bonusdev** [comment]
про private Mutable знаю, я в других классах делал геттер функцию и private поле, просто забыл :)

**Comment by bonusdev** [comment]
[Fixed](https://github.com/bonusdev/BattleOfMindsGame/commit/eae60f03cc1f342950eb8fd5cf35547288780803)
